# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name:  Qwen 3.6 Agent (35B-A3B)
    provider: ollama
    model: qwen3.6:35b-a3b
  - name: Qwen 3.6 Agent (35B-A3B)
    provider: ollama
    model: qwen3.6:35b-a3b
    roles:
      - apply
      - autocomplete
      - chat
      - edit
    defaultCompletionOptions:
      contextLength: 32000
      maxTokens: 64000
    capabilities:
      - tool_use
      - image_input
